# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import phxpf_pb2 as phxpf__pb2


class PhxPFServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Filter = channel.unary_unary(
        '/phxpf.PhxPFServer/Filter',
        request_serializer=phxpf__pb2.PhxPFOperator.SerializeToString,
        response_deserializer=phxpf__pb2.PhxPFResponse.FromString,
        )
    self.Update = channel.unary_unary(
        '/phxpf.PhxPFServer/Update',
        request_serializer=phxpf__pb2.PhxPFOperator.SerializeToString,
        response_deserializer=phxpf__pb2.PhxPFResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/phxpf.PhxPFServer/Delete',
        request_serializer=phxpf__pb2.PhxPFOperator.SerializeToString,
        response_deserializer=phxpf__pb2.PhxPFResponse.FromString,
        )
    self.FilterOne = channel.unary_unary(
        '/phxpf.PhxPFServer/FilterOne',
        request_serializer=phxpf__pb2.PhxPFSingleOperator.SerializeToString,
        response_deserializer=phxpf__pb2.PhxPFSingleResponse.FromString,
        )
    self.UpdateOne = channel.unary_unary(
        '/phxpf.PhxPFServer/UpdateOne',
        request_serializer=phxpf__pb2.PhxPFSingleOperator.SerializeToString,
        response_deserializer=phxpf__pb2.PhxPFSingleResponse.FromString,
        )
    self.DeleteOne = channel.unary_unary(
        '/phxpf.PhxPFServer/DeleteOne',
        request_serializer=phxpf__pb2.PhxPFSingleOperator.SerializeToString,
        response_deserializer=phxpf__pb2.PhxPFSingleResponse.FromString,
        )
    self.IsMaster = channel.unary_unary(
        '/phxpf.PhxPFServer/IsMaster',
        request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        response_deserializer=phxpf__pb2.PhxIAmMaster.FromString,
        )


class PhxPFServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Filter(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FilterOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteOne(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def IsMaster(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PhxPFServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Filter': grpc.unary_unary_rpc_method_handler(
          servicer.Filter,
          request_deserializer=phxpf__pb2.PhxPFOperator.FromString,
          response_serializer=phxpf__pb2.PhxPFResponse.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=phxpf__pb2.PhxPFOperator.FromString,
          response_serializer=phxpf__pb2.PhxPFResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=phxpf__pb2.PhxPFOperator.FromString,
          response_serializer=phxpf__pb2.PhxPFResponse.SerializeToString,
      ),
      'FilterOne': grpc.unary_unary_rpc_method_handler(
          servicer.FilterOne,
          request_deserializer=phxpf__pb2.PhxPFSingleOperator.FromString,
          response_serializer=phxpf__pb2.PhxPFSingleResponse.SerializeToString,
      ),
      'UpdateOne': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateOne,
          request_deserializer=phxpf__pb2.PhxPFSingleOperator.FromString,
          response_serializer=phxpf__pb2.PhxPFSingleResponse.SerializeToString,
      ),
      'DeleteOne': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteOne,
          request_deserializer=phxpf__pb2.PhxPFSingleOperator.FromString,
          response_serializer=phxpf__pb2.PhxPFSingleResponse.SerializeToString,
      ),
      'IsMaster': grpc.unary_unary_rpc_method_handler(
          servicer.IsMaster,
          request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
          response_serializer=phxpf__pb2.PhxIAmMaster.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'phxpf.PhxPFServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
